stages:
  - lint_prettier
  - build
  - deploy

### TEST JOBS ###
Lint Check:
  extends: .lint
.lint:
  extends: .base_test
  script:
    - npm run lint-check

.base_test:
  stage: lint_prettier
  image: node:10.20.0
  cache:
    paths:
      - node_modules
  before_script:
    - yarn

